"""empty message

Revision ID: 0aaf8f514d26
Revises: 1576a86814c5
Create Date: 2024-07-10 07:52:40.135130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aaf8f514d26'
down_revision: Union[str, None] = '1576a86814c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_task', sa.Column('quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_task', 'quality')
    # ### end Alembic commands ###
