"""empty message

Revision ID: 49f0252596c0
Revises: dd5249f0c5c4
Create Date: 2024-10-16 06:13:48.001617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f0252596c0'
down_revision: Union[str, None] = 'dd5249f0c5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_task', sa.Column('importance_list', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_task', 'importance_list')
    # ### end Alembic commands ###
