"""empty message

Revision ID: dd5249f0c5c4
Revises: 0aaf8f514d26
Create Date: 2024-10-16 05:48:47.732405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd5249f0c5c4'
down_revision: Union[str, None] = '0aaf8f514d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_task', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_task', 'payload')
    # ### end Alembic commands ###
