export enum HardFeatures {
    "pandas" = "pandas",
    "matplotlib" = "matplotlib",
    "prometheus" = "prometheus",
    "big data" = "big data",
    "opencv" = "opencv",
    "apache kafka" = "apache kafka",
    "mat_statistic" = "mat_statistic",
    "nosql" = "nosql",
    "pytorch" = "pytorch",
    "numpy" = "numpy",
    "docker" = "docker",
    "git" = "git",
    "bazy dannykh" = "bazy dannykh",
    "api" = "api",
    "sql" = "sql",
    "postgresql" = "postgresql",
    "mashinnoe obuchenie" = "mashinnoe obuchenie",
    "python" = "python",
    "iskusstvennyy intellekt" = "iskusstvennyy intellekt",
}
